name: 'YASS static site generator'
description: 'A GitHub Action to generate a static site based on YASS specifications'
inputs:
  yass-config-path:
    description: 'Path for YASS configuration'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.yass-config-path }}
