name: 'YASS static site generator'
description: 'A GitHub Action to generate a static site based on YASS specifications'
branding:
  icon: 'align-left'
  color: 'orange'
inputs:
  yass-config-path:
    description: 'Path for YASS configuration'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: astral-sh/setup-uv@v6
    - name: generate static site
      shell: bash
      run: |
        uv run generate_site.py "${{ inputs.yass-config-path }}"
